
# hdf5 stuff

SET(HDF5_USE_STATIC_LIBRARIES FALSE)
IF(WIN32)
  FIND_PACKAGE(HDF5 COMPONENTS CXX REQUIRED NO_MODULE)
ELSE(WIN32)
  FIND_PACKAGE(HDF5 COMPONENTS CXX )
  IF (NOT HDF5_FOUND)
  FIND_PACKAGE(HDF5 COMPONENTS CXX REQUIRED NO_MODULE)
  ENDIF(NOT HDF5_FOUND)
ENDIF(WIN32)
   


SET(STATISMO_LIBRARIES ${VTK_LIBRARIES}  ${HDF5_LIBRARIES})
SET(STATISMO_INCLUDE_DIR ${STATISMO_DIR} ${STATISMO_DIR}/3rdParty ${HDF5_INCLUDE_DIR} ${HDF5_INCLUDE_DIR_CPP})
SET(STATISMO_LIBRARY_DIR  ${HDF5_LIBRARY_DIR})
