
# hdf5 stuff

SET (HDF5_INCLUDE_DIR ${STATISMO_DIR}/3rdParty/HDF5/include)
SET (HDF5_INCLUDE_DIR_CPP ${HDF5_INCLUDE_DIR}/cpp)
SET (HDF5_LIBRARY_DIR ${STATISMO_DIR}/3rdParty/HDF5/lib)
SET (HDF5_LIBRARIES hdf5 hdf5_cpp)

SET(STATISMO_LIBRARIES   ${HDF5_LIBRARIES})
SET(STATISMO_INCLUDE_DIR ${STATISMO_DIR} ${STATISMO_DIR}/3rdParty ${HDF5_INCLUDE_DIR} ${HDF5_INCLUDE_DIR_CPP})
SET(STATISMO_LIBRARY_DIR  ${HDF5_LIBRARY_DIR})
	
