message( "External project - HDF5" )

set( HDF5_DOWNLOAD_VERS "1.8" )
set( HDF5_DOWNLOAD_PATCH 20 )
set( HDF5_DOWNLOAD_SH256 6ed660ccd2bc45aa808ea72e08f33cc64009e9dd4e3a372b53438b210312e8d9)

ExternalProject_Add( HDF5
  SOURCE_DIR ${CMAKE_BINARY_DIR}/HDF5
  BINARY_DIR ${CMAKE_BINARY_DIR}/HDF5-build
  URL "http://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_DOWNLOAD_VERS}/hdf5-${HDF5_DOWNLOAD_VERS}.${HDF5_DOWNLOAD_PATCH}/src/hdf5-${HDF5_DOWNLOAD_VERS}.${HDF5_DOWNLOAD_PATCH}.tar.gz"
  URL_HASH "SHA256=${HDF5_DOWNLOAD_SH256}"
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF
    -DHDF5_BUILD_CPP_LIB:BOOL=ON
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DHDF5_BUILD_TOOLS:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DEPENDENCIES_DIR}
  INSTALL_DIR ${INSTALL_DEPENDENCIES_DIR}
)

if( WIN32 )
  set( HDF5_DIR ${INSTALL_DEPENDENCIES_DIR}/cmake/hdf5/ )
else()
  set( HDF5_DIR ${INSTALL_DEPENDENCIES_DIR}/share/cmake/hdf5/ )
endif()

