message("External project - VTK")

set(_vtkOptions ${VTK_EXTRA_OPTIONS})

if(APPLE)
  set(_vtkOptions ${_vtkOptions} -DVTK_REQUIRED_OBJCXX_FLAGS:STRING="")
endif()

ExternalProject_Add(VTK
  GIT_REPOSITORY https://github.com/Kitware/VTK.git
  GIT_TAG v8.2.0
  SOURCE_DIR VTK
  BINARY_DIR VTK-build
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  CMAKE_GENERATOR ${EP_CMAKE_GENERATOR}
  CMAKE_ARGS
    ${ep_common_args}
    ${_vtkOptions}
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DBUILD_TESTING:BOOL=OFF
    -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}
    -DVTK_BUILD_ALL_MODULES:BOOL=OFF
    -DVTK_USE_SYSTEM_HDF5:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_DEPENDENCIES_DIR}
)